export const FETCH_POSTS_LOADING = "FETCH_POSTS_LOADING";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POST_LOADING = "FETCH_POST_LOADING";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
