export const FETCH_PROFILE_LOADING = "FETCH_PROFILE_LOADING";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_USER_TRACKS_LOADING = "FETCH_USER_TRACKS_LOADING";
export const FETCH_USER_TRACKS_SUCCESS = "FETCH_USER_TRACKS_SUCCESS";
